import type { Metadata } from 'next'

import './globals.css'
import localFont from 'next/font/local'
const dosis = localFont({
  src: '../public/fonts/static/Dosis-SemiBold.ttf',
  display: 'swap',
  weight: '900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${dosis.className}`}>
        {children}
        <script
          data-liveedit-widget
          data-project="b49f3bc6-9011-480e-97e9-80b68b10f6aa"
          dangerouslySetInnerHTML={{
            __html: `
const PROJECT_ID = "b49f3bc6-9011-480e-97e9-80b68b10f6aa";
const API_ENDPOINT = "https://ai-editor-backend.vercel.app/api/chat";

(function () {
  const PROJECT_ID = "b49f3bc6-9011-480e-97e9-80b68b10f6aa";
  const API_ENDPOINT = "https://ai-editor-backend.vercel.app/api/chat";

  const conversation = [];
  let pendingChange = null;
  let isWaiting = false;

  const host = document.createElement("div");
  host.id = "chat-widget-host";
  host.style.cssText = "position:fixed;bottom:24px;right:24px;z-index:999999;display:flex;flex-direction:column;align-items:flex-end;";
  document.body.appendChild(host);

  const shadow = host.attachShadow({ mode: "open" });

  const style = document.createElement("style");
  style.textContent = \`
    *{box-sizing:border-box;margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;}
    .bubble-btn{
      width:56px;height:56px;border-radius:50%;background:#1a1a1a;border:none;cursor:pointer;
      display:flex;align-items:center;justify-content:center;box-shadow:0 4px 16px rgba(0,0,0,0.25);
      transition:transform 0.2s,box-shadow 0.2s;flex-shrink:0;
    }
    .bubble-btn:hover{transform:scale(1.08);box-shadow:0 6px 20px rgba(0,0,0,0.32);}
    .bubble-btn svg{width:26px;height:26px;fill:white;}
    .panel{
      width:360px;height:520px;background:#fff;border-radius:16px;
      box-shadow:0 8px 40px rgba(0,0,0,0.18);display:flex;flex-direction:column;
      margin-bottom:12px;overflow:hidden;
      transform-origin:bottom right;
      transition:transform 0.28s cubic-bezier(0.34,1.56,0.64,1),opacity 0.22s ease;
    }
    .panel.hidden{transform:scale(0.7) translateY(40px);opacity:0;pointer-events:none;}
    .panel.visible{transform:scale(1) translateY(0);opacity:1;pointer-events:all;}
    .header{
      background:#1a1a1a;color:#fff;padding:16px 18px;display:flex;
      align-items:center;justify-content:space-between;flex-shrink:0;
    }
    .header-title{font-size:15px;font-weight:600;letter-spacing:0.01em;}
    .close-btn{
      background:none;border:none;cursor:pointer;color:#fff;opacity:0.75;
      display:flex;align-items:center;justify-content:center;padding:4px;border-radius:6px;
      transition:opacity 0.15s;
    }
    .close-btn:hover{opacity:1;}
    .close-btn svg{width:18px;height:18px;fill:white;}
    .messages{flex:1;overflow-y:auto;padding:16px;display:flex;flex-direction:column;gap:10px;}
    .messages::-webkit-scrollbar{width:4px;}
    .messages::-webkit-scrollbar-track{background:transparent;}
    .messages::-webkit-scrollbar-thumb{background:#ddd;border-radius:4px;}
    .msg-row{display:flex;flex-direction:column;}
    .msg-row.user{align-items:flex-end;}
    .msg-row.assistant{align-items:flex-start;}
    .bubble{
      max-width:82%;padding:10px 14px;border-radius:14px;font-size:14px;line-height:1.5;
      word-break:break-word;
    }
    .user .bubble{background:#1a1a1a;color:#fff;border-bottom-right-radius:4px;}
    .assistant .bubble{background:#f0f0f0;color:#1a1a1a;border-bottom-left-radius:4px;}
    .action-btns{display:flex;gap:8px;margin-top:7px;}
    .apply-btn{
      padding:7px 14px;border-radius:8px;background:#1a1a1a;color:#fff;border:none;
      font-size:13px;font-weight:500;cursor:pointer;transition:background 0.15s;
    }
    .apply-btn:hover{background:#333;}
    .cancel-btn{
      padding:7px 14px;border-radius:8px;background:#f0f0f0;color:#555;border:1px solid #ddd;
      font-size:13px;font-weight:500;cursor:pointer;transition:background 0.15s;
    }
    .cancel-btn:hover{background:#e4e4e4;}
    .typing{display:flex;align-items:center;gap:5px;padding:10px 14px;background:#f0f0f0;
      border-radius:14px;border-bottom-left-radius:4px;width:fit-content;}
    .dot{width:7px;height:7px;border-radius:50%;background:#999;animation:bounce 1.2s infinite ease-in-out;}
    .dot:nth-child(1){animation-delay:0s;}
    .dot:nth-child(2){animation-delay:0.2s;}
    .dot:nth-child(3){animation-delay:0.4s;}
    @keyframes bounce{0%,80%,100%{transform:translateY(0);}40%{transform:translateY(-6px);}}
    .input-row{
      display:flex;align-items:center;gap:8px;padding:12px 14px;
      border-top:1px solid #ebebeb;flex-shrink:0;background:#fff;
    }
    .input-field{
      flex:1;border:1px solid #ddd;border-radius:10px;padding:9px 13px;
      font-size:14px;outline:none;resize:none;background:#fafafa;
      transition:border-color 0.15s;line-height:1.4;
    }
    .input-field:focus{border-color:#1a1a1a;background:#fff;}
    .send-btn{
      width:38px;height:38px;border-radius:10px;background:#1a1a1a;border:none;cursor:pointer;
      display:flex;align-items:center;justify-content:center;flex-shrink:0;
      transition:background 0.15s,transform 0.1s;
    }
    .send-btn:hover{background:#333;}
    .send-btn:active{transform:scale(0.94);}
    .send-btn svg{width:17px;height:17px;fill:white;}
    .send-btn:disabled{background:#ccc;cursor:not-allowed;}
  \`;
  shadow.appendChild(style);

  const panel = document.createElement("div");
  panel.className = "panel hidden";
  panel.innerHTML = \`
    <div class="header">
      <span class="header-title">Chat with us</span>
      <button class="close-btn" aria-label="Close chat">
        <svg viewBox="0 0 24 24"><path d="M18.3 5.71a1 1 0 00-1.41 0L12 10.59 7.11 5.7A1 1 0 005.7 7.11L10.59 12 5.7 16.89a1 1 0 001.41 1.41L12 13.41l4.89 4.89a1 1 0 001.41-1.41L13.41 12l4.89-4.89a1 1 0 000-1.4z"/></svg>
      </button>
    </div>
    <div class="messages" id="messages"></div>
    <div class="input-row">
      <input class="input-field" id="input-field" type="text" placeholder="Type a message\u2026" autocomplete="off"/>
      <button class="send-btn" id="send-btn" aria-label="Send">
        <svg viewBox="0 0 24 24"><path d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"/></svg>
      </button>
    </div>
  \`;
  shadow.appendChild(panel);

  const bubbleBtn = document.createElement("button");
  bubbleBtn.className = "bubble-btn";
  bubbleBtn.setAttribute("aria-label", "Open chat");
  bubbleBtn.innerHTML = \`<svg viewBox="0 0 24 24"><path d="M20 2H4C2.9 2 2 2.9 2 4v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm0 12H6l-2 2V4h16v10z"/></svg>\`;
  shadow.appendChild(bubbleBtn);

  const messagesEl = shadow.getElementById("messages");
  const inputField = shadow.getElementById("input-field");
  const sendBtn = shadow.getElementById("send-btn");

  let panelOpen = false;

  function togglePanel() {
    panelOpen = !panelOpen;
    if (panelOpen) {
      panel.classList.remove("hidden");
      panel.classList.add("visible");
      inputField.focus();
    } else {
      panel.classList.remove("visible");
      panel.classList.add("hidden");
    }
  }

  bubbleBtn.addEventListener("click", togglePanel);
  shadow.querySelector(".close-btn").addEventListener("click", togglePanel);

  function escapeHtml(str) {
    return str
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");
  }

  function renderMarkdown(text) {
    let escaped = escapeHtml(text);
    escaped = escaped.replace(/\\*\\*(.+?)\\*\\*/g, "<strong>$1</strong>");
    escaped = escaped.replace(/^[\\-\\*]\\s+(.*)$/gm, "\u2022 $1");
    escaped = escaped.replace(/\\n/g, "<br>");
    return escaped;
  }

  function scrollToBottom() {
    messagesEl.scrollTop = messagesEl.scrollHeight;
  }

  function addMessage(role, text) {
    const row = document.createElement("div");
    row.className = \`msg-row \${role}\`;
    const bubble = document.createElement("div");
    bubble.className = "bubble";
    bubble.innerHTML = renderMarkdown(text);
    row.appendChild(bubble);
    messagesEl.appendChild(row);
    scrollToBottom();
    return row;
  }

  function addTypingIndicator() {
    const row = document.createElement("div");
    row.className = "msg-row assistant";
    row.innerHTML = \`<div class="typing"><div class="dot"></div><div class="dot"></div><div class="dot"></div></div>\`;
    messagesEl.appendChild(row);
    scrollToBottom();
    return row;
  }

  function addConfirmationButtons(msgRow, change) {
    const btnRow = document.createElement("div");
    btnRow.className = "action-btns";

    const applyBtn = document.createElement("button");
    applyBtn.className = "apply-btn";
    applyBtn.textContent = "\u2705 Apply";

    const cancelBtn = document.createElement("button");
    cancelBtn.className = "cancel-btn";
    cancelBtn.textContent = "\u274c Cancel";

    btnRow.appendChild(applyBtn);
    btnRow.appendChild(cancelBtn);
    msgRow.appendChild(btnRow);
    scrollToBottom();

    applyBtn.addEventListener("click", async () => {
      btnRow.remove();
      pendingChange = null;
      const typingRow = addTypingIndicator();
      try {
        const res = await fetch(API_ENDPOINT, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ projectId: PROJECT_ID, message: "confirm", confirmChangeId: change.changeId }),
        });
        typingRow.remove();
        if (!res.ok) throw new Error("Network error");
        const data = await res.json();
        const reply = data.reply || "";
        conversation.push({ role: "assistant", content: reply });
        addMessage("assistant", reply);
      } catch (e) {
        typingRow.remove();
        addMessage("assistant", "Sorry, something went wrong. Please try again.");
      }
      setInputEnabled(true);
    });

    cancelBtn.addEventListener("click", () => {
      btnRow.remove();
      pendingChange = null;
      addMessage("assistant", "Change cancelled.");
      setInputEnabled(true);
    });
  }

  function setInputEnabled(enabled) {
    isWaiting = !enabled;
    inputField.disabled = !enabled;
    sendBtn.disabled = !enabled;
  }

  async function sendMessage() {
    const text = inputField.value.trim();
    if (!text || isWaiting) return;

    inputField.value = "";
    conversation.push({ role: "user", content: text });
    addMessage("user", text);
    setInputEnabled(false);

    const typingRow = addTypingIndicator();

    try {
      const res = await fetch(API_ENDPOINT, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ projectId: PROJECT_ID, message: text }),
      });

      typingRow.remove();

      if (!res.ok) throw new Error("Network error");

      const data = await res.json();
      const reply = data.reply || "";
      conversation.push({ role: "assistant", content: reply });
      const msgRow = addMessage("assistant", reply);

      if (data.pendingChange) {
        pendingChange = data.pendingChange;
        setInputEnabled(false);
        addConfirmationButtons(msgRow, pendingChange);
      } else {
        setInputEnabled(true);
      }
    } catch (e) {
      typingRow.remove();
      addMessage("assistant", "Sorry, something went wrong. Please try again.");
      setInputEnabled(true);
    }
  }

  sendBtn.addEventListener("click", sendMessage);
  inputField.addEventListener("keydown", (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  });
})();
`,
          }}
        />
      </body>
    </html>
  )
}
