import type { Metadata } from 'next'

import './globals.css'
import localFont from 'next/font/local'
const dosis = localFont({
  src: '../public/fonts/static/Dosis-SemiBold.ttf',
  display: 'swap',
  weight: '900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const LIVEEDIT_WIDGET_JS = `const PROJECT_ID = "48cb8dd7-0c81-4727-8256-13acd5e976e7";
const API_ENDPOINT = "https://ai-editor-backend-vsqh.onrender.com/api/chat";

(function () {
  const PROJECT_ID = "48cb8dd7-0c81-4727-8256-13acd5e976e7";
  const API_ENDPOINT = "https://ai-editor-backend-vsqh.onrender.com/api/chat";

  const conversation = [];
  let pendingChange = null;
  let isWaiting = false;

  // Create host element
  const host = document.createElement("div");
  host.id = "chat-widget-host";
  host.style.cssText = "position:fixed;bottom:24px;right:24px;z-index:999999;display:flex;flex-direction:column;align-items:flex-end;";
  document.body.appendChild(host);

  // Attach Shadow DOM
  const shadow = host.attachShadow({ mode: "open" });

  // Styles
  const style = document.createElement("style");
  style.textContent = \`
    *{box-sizing:border-box;margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;}

    #bubble{
      width:56px;height:56px;border-radius:50%;background:#111;border:none;cursor:pointer;
      display:flex;align-items:center;justify-content:center;box-shadow:0 4px 16px rgba(0,0,0,.3);
      transition:transform .2s;flex-shrink:0;
    }
    #bubble:hover{transform:scale(1.08);}
    #bubble svg{width:26px;height:26px;fill:white;}

    #panel{
      width:360px;height:520px;background:#fff;border-radius:16px;
      box-shadow:0 8px 40px rgba(0,0,0,.18);display:flex;flex-direction:column;
      overflow:hidden;margin-bottom:12px;
      transform-origin:bottom right;
      transition:transform .25s cubic-bezier(.4,0,.2,1),opacity .25s;
    }
    #panel.hidden{transform:scale(.85) translateY(20px);opacity:0;pointer-events:none;}

    #header{
      background:#111;color:#fff;padding:16px 18px;display:flex;align-items:center;
      justify-content:space-between;flex-shrink:0;
    }
    #header-title{font-size:15px;font-weight:600;letter-spacing:.01em;}
    #close-btn{background:none;border:none;cursor:pointer;color:#fff;display:flex;align-items:center;padding:2px;}
    #close-btn svg{width:20px;height:20px;fill:white;}

    #messages{
      flex:1;overflow-y:auto;padding:16px 14px;display:flex;flex-direction:column;gap:10px;
    }
    #messages::-webkit-scrollbar{width:4px;}
    #messages::-webkit-scrollbar-thumb{background:#ddd;border-radius:4px;}

    .msg-row{display:flex;width:100%;}
    .msg-row.user{justify-content:flex-end;}
    .msg-row.assistant{justify-content:flex-start;}

    .bubble-msg{
      max-width:78%;padding:10px 13px;border-radius:14px;font-size:13.5px;line-height:1.5;word-break:break-word;
    }
    .msg-row.user .bubble-msg{background:#111;color:#fff;border-bottom-right-radius:4px;}
    .msg-row.assistant .bubble-msg{background:#f0f0f0;color:#111;border-bottom-left-radius:4px;}

    .action-row{display:flex;gap:8px;margin-top:4px;padding-left:4px;}
    .action-btn{
      border:none;border-radius:8px;padding:7px 13px;font-size:12.5px;cursor:pointer;font-weight:600;transition:opacity .15s;
    }
    .action-btn:hover{opacity:.85;}
    .btn-confirm{background:#111;color:#fff;}
    .btn-undo{background:#eee;color:#444;}

    .typing-dots{display:flex;align-items:center;gap:4px;height:18px;padding:0 2px;}
    .typing-dots span{
      width:7px;height:7px;border-radius:50%;background:#999;display:inline-block;
      animation:bounce .9s infinite ease-in-out;
    }
    .typing-dots span:nth-child(2){animation-delay:.15s;}
    .typing-dots span:nth-child(3){animation-delay:.3s;}
    @keyframes bounce{0%,60%,100%{transform:translateY(0);}30%{transform:translateY(-6px);}}

    #input-row{
      display:flex;gap:8px;padding:12px 14px;border-top:1px solid #eee;flex-shrink:0;background:#fff;
    }
    #msg-input{
      flex:1;border:1px solid #ddd;border-radius:10px;padding:9px 12px;font-size:13.5px;outline:none;
      resize:none;height:40px;line-height:1.4;transition:border-color .15s;
    }
    #msg-input:focus{border-color:#111;}
    #send-btn{
      background:#111;color:#fff;border:none;border-radius:10px;padding:0 16px;font-size:13px;
      font-weight:600;cursor:pointer;height:40px;white-space:nowrap;transition:opacity .15s;
    }
    #send-btn:hover{opacity:.85;}
    #send-btn:disabled{opacity:.45;cursor:not-allowed;}
  \`;
  shadow.appendChild(style);

  // Panel
  const panel = document.createElement("div");
  panel.id = "panel";
  panel.classList.add("hidden");

  // Header
  const header = document.createElement("div");
  header.id = "header";
  header.innerHTML = \`
    <span id="header-title">Chat with us</span>
    <button id="close-btn" aria-label="Close chat">
      <svg viewBox="0 0 24 24"><path d="M18 6L6 18M6 6l12 12" stroke="white" stroke-width="2.2" stroke-linecap="round" fill="none"/></svg>
    </button>
  \`;
  panel.appendChild(header);

  // Messages
  const messages = document.createElement("div");
  messages.id = "messages";
  panel.appendChild(messages);

  // Input row
  const inputRow = document.createElement("div");
  inputRow.id = "input-row";
  inputRow.innerHTML = \`
    <input id="msg-input" type="text" placeholder="Type a message…" autocomplete="off"/>
    <button id="send-btn">Send</button>
  \`;
  panel.appendChild(inputRow);
  shadow.appendChild(panel);

  // Bubble
  const bubble = document.createElement("button");
  bubble.id = "bubble";
  bubble.setAttribute("aria-label", "Open chat");
  bubble.innerHTML = \`<svg viewBox="0 0 24 24"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>\`;
  shadow.appendChild(bubble);

  // References
  const msgInput = shadow.getElementById("msg-input");
  const sendBtn = shadow.getElementById("send-btn");
  const closeBtn = shadow.getElementById("close-btn");

  // Toggle panel
  let panelOpen = false;
  function openPanel() {
    panelOpen = true;
    panel.classList.remove("hidden");
    msgInput.focus();
  }
  function closePanel() {
    panelOpen = false;
    panel.classList.add("hidden");
  }

  bubble.addEventListener("click", () => panelOpen ? closePanel() : openPanel());
  closeBtn.addEventListener("click", closePanel);

  // Markdown-lite renderer
  function renderMarkdown(text) {
    // Escape HTML first
    let html = text
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");
    // Bold
    html = html.replace(/\\*\\*(.+?)\\*\\*/g, "<strong>$1</strong>");
    // Bullet points: lines starting with - or *
    html = html.replace(/^[-*]\\s+(.+)$/gm, "• $1");
    // Newlines
    html = html.replace(/\\n/g, "<br>");
    return html;
  }

  // Append message bubble
  function appendMessage(role, text, id) {
    const row = document.createElement("div");
    row.classList.add("msg-row", role);
    if (id) row.id = id;

    const bbl = document.createElement("div");
    bbl.classList.add("bubble-msg");
    bbl.innerHTML = renderMarkdown(text);
    row.appendChild(bbl);
    messages.appendChild(row);
    scrollToBottom();
    return row;
  }

  // Typing indicator
  function showTyping() {
    const row = document.createElement("div");
    row.classList.add("msg-row", "assistant");
    row.id = "typing-row";
    const bbl = document.createElement("div");
    bbl.classList.add("bubble-msg");
    bbl.innerHTML = \`<div class="typing-dots"><span></span><span></span><span></span></div>\`;
    row.appendChild(bbl);
    messages.appendChild(row);
    scrollToBottom();
  }

  function hideTyping() {
    const t = shadow.getElementById("typing-row");
    if (t) t.remove();
  }

  function scrollToBottom() {
    messages.scrollTop = messages.scrollHeight;
  }

  // Apply DOM operations to HOST page
  function applyDomOperations(ops) {
    if (!ops || !ops.length) return;
    ops.forEach(op => {
      try {
        const el = document.querySelector(op.selector);
        if (!el) return;
        switch (op.op) {
          case "replace_content":
            el.innerHTML = op.html;
            break;
          case "replace_attr":
            el.setAttribute(op.attr, op.value);
            break;
          case "insert_after":
            el.insertAdjacentHTML("afterend", op.html);
            break;
          case "insert_before":
            el.insertAdjacentHTML("beforebegin", op.html);
            break;
          case "remove":
            el.remove();
            break;
          case "add_class":
            el.classList.add(...(Array.isArray(op.classes) ? op.classes : [op.classes]));
            break;
          case "remove_class":
            el.classList.remove(...(Array.isArray(op.classes) ? op.classes : [op.classes]));
            break;
          case "replace_style":
            Object.assign(el.style, op.styles);
            break;
        }
      } catch (e) {
        console.warn("DOM op failed:", op, e);
      }
    });
  }

  // Render confirmation buttons
  function renderConfirmation(pc) {
    const actionRow = document.createElement("div");
    actionRow.classList.add("action-row");
    actionRow.id = "action-row";

    const confirmBtn = document.createElement("button");
    confirmBtn.classList.add("action-btn", "btn-confirm");
    confirmBtn.textContent = "✅ Create PR";

    const undoBtn = document.createElement("button");
    undoBtn.classList.add("action-btn", "btn-undo");
    undoBtn.textContent = "↩️ Undo";

    confirmBtn.addEventListener("click", async () => {
      actionRow.remove();
      pendingChange = null;
      await sendConfirmation(pc.changeId);
    });

    undoBtn.addEventListener("click", () => {
      actionRow.remove();
      pendingChange = null;
      appendMessage("assistant", "Change reverted.");
      location.reload();
    });

    actionRow.appendChild(confirmBtn);
    actionRow.appendChild(undoBtn);
    messages.appendChild(actionRow);
    scrollToBottom();
  }

  // Send confirmation request
  async function sendConfirmation(changeId) {
    setWaiting(true);
    showTyping();
    try {
      const res = await fetch(API_ENDPOINT, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ projectId: PROJECT_ID, message: "confirm", confirmChangeId: changeId })
      });
      const data = await res.json();
      hideTyping();
      if (data.domOperations) applyDomOperations(data.domOperations);
      appendMessage("assistant", data.reply || "Done!");
      if (data.pendingChange) {
        pendingChange = data.pendingChange;
        renderConfirmation(pendingChange);
      }
    } catch (e) {
      hideTyping();
      appendMessage("assistant", "Sorry, something went wrong. Please try again.");
    }
    setWaiting(false);
  }

  // Set waiting state
  function setWaiting(val) {
    isWaiting = val;
    sendBtn.disabled = val;
    msgInput.disabled = val;
  }

  // Send user message
  async function sendMessage() {
    const text = msgInput.value.trim();
    if (!text || isWaiting) return;

    msgInput.value = "";
    appendMessage("user", text);
    conversation.push({ role: "user", content: text });

    // Compress the full page HTML using CompressionStream (supported in all modern browsers)
    let pageHtmlCompressed = "";
    try {
      const fullHtml = document.documentElement.outerHTML;
      if (typeof CompressionStream !== "undefined") {
        const stream = new CompressionStream("gzip");
        const writer = stream.writable.getWriter();
        writer.write(new TextEncoder().encode(fullHtml));
        writer.close();
        const chunks = [];
        const reader = stream.readable.getReader();
        let done = false;
        while (!done) {
          const { value, done: d } = await reader.read();
          if (value) chunks.push(value);
          done = d;
        }
        const compressed = new Uint8Array(chunks.reduce((acc, c) => acc + c.length, 0));
        let offset = 0;
        for (const chunk of chunks) { compressed.set(chunk, offset); offset += chunk.length; }
        pageHtmlCompressed = btoa(String.fromCharCode(...compressed));
      }
    } catch(e) { console.warn("[liveedit] compression failed", e); }

    setWaiting(true);
    showTyping();

    try {
      const res = await fetch(API_ENDPOINT, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ projectId: PROJECT_ID, message: text, pageHtmlCompressed })
      });

      const data = await res.json();
      hideTyping();

      if (data.domOperations) applyDomOperations(data.domOperations);

      const reply = data.reply || "No response.";
      conversation.push({ role: "assistant", content: reply });
      appendMessage("assistant", reply);

      if (data.pendingChange) {
        pendingChange = data.pendingChange;
        renderConfirmation(pendingChange);
      }
    } catch (e) {
      hideTyping();
      appendMessage("assistant", "Sorry, something went wrong. Please try again.");
    }

    setWaiting(false);
  }

  sendBtn.addEventListener("click", sendMessage);
  msgInput.addEventListener("keydown", e => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  });

})();`

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${dosis.className}`}>
        {children}
        <script
          data-liveedit-widget
          data-project="48cb8dd7-0c81-4727-8256-13acd5e976e7"
          dangerouslySetInnerHTML={{ __html: LIVEEDIT_WIDGET_JS }}
        />
      
        <script dangerouslySetInnerHTML={{ __html: `const PROJECT_ID = "48cb8dd7-0c81-4727-8256-13acd5e976e7";
const API_ENDPOINT = "https://ai-editor-backend-vsqh.onrender.com/api/chat";

(function () {
  const host = document.createElement("div");
  host.id = "__chat_widget_host__";
  host.style.cssText = "position:fixed;bottom:24px;right:24px;z-index:999999;display:flex;flex-direction:column;align-items:flex-end;";
  document.body.appendChild(host);

  const shadow = host.attachShadow({ mode: "open" });

  const style = document.createElement("style");
  style.textContent = \`
    *{box-sizing:border-box;margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;}

    #bubble{
      width:56px;height:56px;border-radius:50%;background:#1a1a1a;border:none;cursor:pointer;
      display:flex;align-items:center;justify-content:center;box-shadow:0 4px 16px rgba(0,0,0,0.25);
      transition:transform 0.2s,box-shadow 0.2s;flex-shrink:0;
    }
    #bubble:hover{transform:scale(1.08);box-shadow:0 6px 20px rgba(0,0,0,0.32);}
    #bubble svg{width:26px;height:26px;fill:white;}

    #panel{
      width:360px;height:520px;background:#fff;border-radius:16px;
      box-shadow:0 8px 40px rgba(0,0,0,0.18);display:flex;flex-direction:column;overflow:hidden;
      margin-bottom:12px;
      transform:translateY(20px) scale(0.97);opacity:0;pointer-events:none;
      transition:transform 0.28s cubic-bezier(.4,0,.2,1),opacity 0.28s cubic-bezier(.4,0,.2,1);
    }
    #panel.open{transform:translateY(0) scale(1);opacity:1;pointer-events:all;}

    #header{
      background:#1a1a1a;color:#fff;padding:16px 18px;display:flex;align-items:center;
      justify-content:space-between;flex-shrink:0;
    }
    #header-title{font-size:15px;font-weight:600;letter-spacing:0.01em;}
    #close-btn{
      background:none;border:none;color:#fff;cursor:pointer;padding:4px;border-radius:6px;
      display:flex;align-items:center;justify-content:center;opacity:0.8;transition:opacity 0.15s;
    }
    #close-btn:hover{opacity:1;}
    #close-btn svg{width:18px;height:18px;stroke:white;fill:none;}

    #messages{
      flex:1;overflow-y:auto;padding:16px 14px;display:flex;flex-direction:column;gap:10px;
      scroll-behavior:smooth;
    }
    #messages::-webkit-scrollbar{width:5px;}
    #messages::-webkit-scrollbar-track{background:transparent;}
    #messages::-webkit-scrollbar-thumb{background:#ddd;border-radius:99px;}

    .msg{max-width:82%;padding:10px 13px;border-radius:14px;font-size:13.5px;line-height:1.5;word-break:break-word;}
    .msg.user{align-self:flex-end;background:#1a1a1a;color:#fff;border-bottom-right-radius:4px;}
    .msg.assistant{align-self:flex-start;background:#f0f0f0;color:#1a1a1a;border-bottom-left-radius:4px;}

    .msg-confirm{align-self:flex-start;display:flex;flex-direction:column;gap:8px;max-width:82%;}
    .msg-confirm .confirm-text{background:#f0f0f0;color:#1a1a1a;padding:10px 13px;border-radius:14px;border-bottom-left-radius:4px;font-size:13.5px;line-height:1.5;}
    .confirm-buttons{display:flex;gap:8px;}
    .confirm-btn{
      padding:7px 14px;border-radius:8px;border:none;cursor:pointer;font-size:13px;font-weight:500;
      transition:opacity 0.15s,transform 0.1s;
    }
    .confirm-btn:hover{opacity:0.85;transform:translateY(-1px);}
    .confirm-btn.pr{background:#1a1a1a;color:#fff;}
    .confirm-btn.undo{background:#e5e5e5;color:#1a1a1a;}

    .typing{align-self:flex-start;background:#f0f0f0;padding:11px 14px;border-radius:14px;border-bottom-left-radius:4px;display:flex;gap:5px;align-items:center;}
    .typing span{width:7px;height:7px;border-radius:50%;background:#888;display:inline-block;animation:bounce 1.2s infinite ease-in-out;}
    .typing span:nth-child(1){animation-delay:0s;}
    .typing span:nth-child(2){animation-delay:0.18s;}
    .typing span:nth-child(3){animation-delay:0.36s;}
    @keyframes bounce{0%,80%,100%{transform:translateY(0);}40%{transform:translateY(-6px);}}

    #input-row{
      display:flex;gap:8px;padding:12px 14px;border-top:1px solid #ebebeb;flex-shrink:0;background:#fff;
    }
    #user-input{
      flex:1;border:1.5px solid #e0e0e0;border-radius:10px;padding:9px 12px;font-size:13.5px;
      outline:none;resize:none;transition:border-color 0.18s;line-height:1.45;max-height:100px;overflow-y:auto;
      color:#1a1a1a;
    }
    #user-input:focus{border-color:#1a1a1a;}
    #send-btn{
      background:#1a1a1a;color:#fff;border:none;border-radius:10px;padding:9px 15px;cursor:pointer;
      font-size:13.5px;font-weight:500;transition:opacity 0.15s,transform 0.1s;flex-shrink:0;
    }
    #send-btn:hover{opacity:0.85;transform:translateY(-1px);}
    #send-btn:active{transform:translateY(0);}
    #send-btn:disabled{opacity:0.45;cursor:not-allowed;transform:none;}
  \`;
  shadow.appendChild(style);

  const panel = document.createElement("div");
  panel.id = "panel";
  panel.innerHTML = \`
    <div id="header">
      <span id="header-title">Chat with us</span>
      <button id="close-btn" aria-label="Close chat">
        <svg viewBox="0 0 24 24" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">
          <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
        </svg>
      </button>
    </div>
    <div id="messages"></div>
    <div id="input-row">
      <textarea id="user-input" rows="1" placeholder="Type a message…"></textarea>
      <button id="send-btn">Send</button>
    </div>
  \`;

  const bubble = document.createElement("button");
  bubble.id = "bubble";
  bubble.setAttribute("aria-label", "Open chat");
  bubble.innerHTML = \`<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
    <path d="M20 2H4C2.9 2 2 2.9 2 4v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2z"/>
  </svg>\`;

  shadow.appendChild(panel);
  shadow.appendChild(bubble);

  const messagesEl = shadow.getElementById("messages");
  const userInput = shadow.getElementById("user-input");
  const sendBtn = shadow.getElementById("send-btn");
  const closeBtn = shadow.getElementById("close-btn");

  let isOpen = false;
  let isWaiting = false;
  const conversation = [];

  function togglePanel() {
    isOpen = !isOpen;
    panel.classList.toggle("open", isOpen);
    if (isOpen) {
      setTimeout(() => userInput.focus(), 280);
    }
  }

  bubble.addEventListener("click", togglePanel);
  closeBtn.addEventListener("click", togglePanel);

  function formatText(text) {
    return text
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      .replace(/\n/g, "<br>");
  }

  function appendMessage(role, text) {
    const div = document.createElement("div");
    div.classList.add("msg", role);
    div.innerHTML = formatText(text);
    messagesEl.appendChild(div);
    scrollToBottom();
    return div;
  }

  function showTyping() {
    const div = document.createElement("div");
    div.classList.add("typing");
    div.id = "__typing__";
    div.innerHTML = "<span></span><span></span><span></span>";
    messagesEl.appendChild(div);
    scrollToBottom();
    return div;
  }

  function removeTyping() {
    const t = shadow.getElementById("__typing__");
    if (t) t.remove();
  }

  function scrollToBottom() {
    messagesEl.scrollTop = messagesEl.scrollHeight;
  }

  function showConfirmButtons(pendingChange, replyText) {
    const wrapper = document.createElement("div");
    wrapper.classList.add("msg-confirm");

    const textDiv = document.createElement("div");
    textDiv.classList.add("confirm-text");
    textDiv.innerHTML = formatText(replyText);

    const btnRow = document.createElement("div");
    btnRow.classList.add("confirm-buttons");

    const prBtn = document.createElement("button");
    prBtn.classList.add("confirm-btn", "pr");
    prBtn.textContent = "✅ Create PR";

    const undoBtn = document.createElement("button");
    undoBtn.classList.add("confirm-btn", "undo");
    undoBtn.textContent = "↩️ Undo";

    btnRow.appendChild(prBtn);
    btnRow.appendChild(undoBtn);
    wrapper.appendChild(textDiv);
    wrapper.appendChild(btnRow);
    messagesEl.appendChild(wrapper);
    scrollToBottom();

    prBtn.addEventListener("click", async () => {
      prBtn.disabled = true;
      undoBtn.disabled = true;
      prBtn.textContent = "Sending…";
      try {
        const res = await fetch(API_ENDPOINT, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ projectId: PROJECT_ID, message: "confirm", confirmChangeId: pendingChange.id })
        });
        const data = await res.json();
        wrapper.remove();
        appendMessage("assistant", data.reply || "Done!");
        conversation.push({ role: "assistant", content: data.reply || "Done!" });
      } catch (e) {
        wrapper.remove();
        appendMessage("assistant", "Sorry, something went wrong. Please try again.");
      }
    });

    undoBtn.addEventListener("click", () => {
      location.reload();
    });
  }

  function applyDomOperations(ops) {
    if (!ops || !Array.isArray(ops)) return;
    ops.forEach(op => {
      try {
        const el = document.querySelector(op.selector);
        if (!el) return;
        if (op.op === "replace_content") el.innerHTML = op.html;
        else if (op.op === "replace_attr") el.setAttribute(op.attr, op.value);
        else if (op.op === "replace_style") Object.assign(el.style, op.styles);
        else if (op.op === "add_class") el.classList.add(...op.classes);
        else if (op.op === "remove_class") el.classList.remove(...op.classes);
        else if (op.op === "insert_after") el.insertAdjacentHTML("afterend", op.html);
        else if (op.op === "remove") el.remove();
      } catch (e) {
        console.warn("[ChatWidget] DOM op failed:", op, e);
      }
    });
  }

  async function sendMessage() {
    const text = userInput.value.trim();
    if (!text || isWaiting) return;

    userInput.value = "";
    userInput.style.height = "auto";
    isWaiting = true;
    sendBtn.disabled = true;

    conversation.push({ role: "user", content: text });
    appendMessage("user", text);

    const typing = showTyping();

    let pageHtml = "";
    try { pageHtml = document.documentElement.outerHTML.slice(0, 200000); } catch (e) {}

    try {
      const res = await fetch(API_ENDPOINT, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ projectId: PROJECT_ID, message: text, pageHtml })
      });

      removeTyping();

      if (!res.ok) throw new Error("HTTP " + res.status);

      const data = await res.json();

      if (data.domOperations) {
        applyDomOperations(data.domOperations);
      }

      if (data.pendingChange) {
        showConfirmButtons(data.pendingChange, data.reply || "");
        conversation.push({ role: "assistant", content: data.reply || "" });
      } else {
        const reply = data.reply || "No response received.";
        appendMessage("assistant", reply);
        conversation.push({ role: "assistant", content: reply });
      }

    } catch (e) {
      removeTyping();
      const errMsg = "Sorry, something went wrong. Please try again.";
      appendMessage("assistant", errMsg);
      conversation.push({ role: "assistant", content: errMsg });
    } finally {
      isWaiting = false;
      sendBtn.disabled = false;
      userInput.focus();
    }
  }

  sendBtn.addEventListener("click", sendMessage);

  userInput.addEventListener("keydown", (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  });

  userInput.addEventListener("input", () => {
    userInput.style.height = "auto";
    userInput.style.height = Math.min(userInput.scrollHeight, 100) + "px";
  });
})();` }} />
      
        <script dangerouslySetInnerHTML={{ __html: `const PROJECT_ID = "48cb8dd7-0c81-4727-8256-13acd5e976e7";
const API_ENDPOINT = "https://ai-editor-backend-vsqh.onrender.com/api/chat";

(function () {
  const host = document.createElement("div");
  host.id = "ai-chat-widget-host";
  host.style.cssText = "position:fixed;bottom:24px;right:24px;z-index:999999;display:flex;flex-direction:column;align-items:flex-end;";
  document.body.appendChild(host);

  const shadow = host.attachShadow({ mode: "open" });

  const style = document.createElement("style");
  style.textContent = \`
    *{box-sizing:border-box;margin:0;padding:0;}
    .bubble{
      width:56px;height:56px;border-radius:50%;background:#1a1a1a;
      border:none;cursor:pointer;display:flex;align-items:center;justify-content:center;
      box-shadow:0 4px 16px rgba(0,0,0,0.25);transition:transform 0.2s,box-shadow 0.2s;
      flex-shrink:0;
    }
    .bubble:hover{transform:scale(1.08);box-shadow:0 6px 22px rgba(0,0,0,0.32);}
    .bubble svg{width:26px;height:26px;fill:white;}
    .panel{
      width:360px;height:520px;background:#fff;border-radius:16px;
      box-shadow:0 8px 40px rgba(0,0,0,0.18);display:flex;flex-direction:column;
      overflow:hidden;margin-bottom:12px;
      transform-origin:bottom right;
      transition:transform 0.28s cubic-bezier(0.34,1.56,0.64,1),opacity 0.22s ease;
    }
    .panel.hidden{transform:scale(0.85) translateY(24px);opacity:0;pointer-events:none;}
    .panel.visible{transform:scale(1) translateY(0);opacity:1;pointer-events:all;}
    .header{
      background:#1a1a1a;color:#fff;padding:0 16px;height:54px;
      display:flex;align-items:center;justify-content:space-between;flex-shrink:0;
    }
    .header-title{font-family:system-ui,sans-serif;font-size:15px;font-weight:600;letter-spacing:0.01em;}
    .close-btn{
      background:none;border:none;cursor:pointer;color:#fff;
      display:flex;align-items:center;justify-content:center;
      width:32px;height:32px;border-radius:50%;transition:background 0.15s;
    }
    .close-btn:hover{background:rgba(255,255,255,0.15);}
    .close-btn svg{width:18px;height:18px;fill:white;}
    .messages{
      flex:1;overflow-y:auto;padding:16px 14px;
      display:flex;flex-direction:column;gap:10px;
      font-family:system-ui,sans-serif;font-size:14px;line-height:1.5;
    }
    .messages::-webkit-scrollbar{width:4px;}
    .messages::-webkit-scrollbar-track{background:transparent;}
    .messages::-webkit-scrollbar-thumb{background:#ddd;border-radius:2px;}
    .msg{max-width:82%;padding:9px 13px;border-radius:14px;word-break:break-word;}
    .msg.user{
      align-self:flex-end;background:#1a1a1a;color:#fff;
      border-bottom-right-radius:3px;
    }
    .msg.assistant{
      align-self:flex-start;background:#f0f0f0;color:#1a1a1a;
      border-bottom-left-radius:3px;
    }
    .msg.error{
      align-self:flex-start;background:#fff0f0;color:#c0392b;
      border:1px solid #fcd0d0;border-bottom-left-radius:3px;
    }
    .typing{align-self:flex-start;background:#f0f0f0;padding:10px 14px;border-radius:14px;border-bottom-left-radius:3px;}
    .typing span{display:inline-block;width:7px;height:7px;border-radius:50%;background:#999;margin:0 2px;animation:bounce 1.2s infinite;}
    .typing span:nth-child(2){animation-delay:0.2s;}
    .typing span:nth-child(3){animation-delay:0.4s;}
    @keyframes bounce{0%,60%,100%{transform:translateY(0);}30%{transform:translateY(-6px);}}
    .confirm-row{display:flex;gap:8px;margin-top:6px;flex-wrap:wrap;}
    .confirm-btn{
      padding:7px 13px;border-radius:8px;border:none;cursor:pointer;
      font-family:system-ui,sans-serif;font-size:13px;font-weight:600;
      transition:opacity 0.15s,transform 0.1s;
    }
    .confirm-btn:hover{opacity:0.85;transform:translateY(-1px);}
    .confirm-btn.pr{background:#1a1a1a;color:#fff;}
    .confirm-btn.undo{background:#e5e5e5;color:#1a1a1a;}
    .input-row{
      display:flex;align-items:center;gap:8px;padding:10px 12px;
      border-top:1px solid #ebebeb;flex-shrink:0;background:#fff;
    }
    .input-field{
      flex:1;border:1.5px solid #e0e0e0;border-radius:10px;
      padding:9px 12px;font-family:system-ui,sans-serif;font-size:14px;
      outline:none;transition:border-color 0.18s;resize:none;
      line-height:1.4;max-height:100px;overflow-y:auto;
      background:#fafafa;color:#1a1a1a;
    }
    .input-field:focus{border-color:#1a1a1a;background:#fff;}
    .send-btn{
      width:38px;height:38px;border-radius:10px;background:#1a1a1a;
      border:none;cursor:pointer;display:flex;align-items:center;justify-content:center;
      flex-shrink:0;transition:opacity 0.15s,transform 0.1s;
    }
    .send-btn:hover{opacity:0.82;transform:translateY(-1px);}
    .send-btn:disabled{opacity:0.4;cursor:not-allowed;transform:none;}
    .send-btn svg{width:18px;height:18px;fill:white;}
  \`;
  shadow.appendChild(style);

  // Panel
  const panel = document.createElement("div");
  panel.className = "panel hidden";

  // Header
  const header = document.createElement("div");
  header.className = "header";
  header.innerHTML = \`
    <span class="header-title">Chat with us</span>
    <button class="close-btn" aria-label="Close chat">
      <svg viewBox="0 0 24 24"><path d="M18 6L6 18M6 6l12 12" stroke="white" stroke-width="2.2" stroke-linecap="round" fill="none"/></svg>
    </button>
  \`;
  panel.appendChild(header);

  // Messages
  const messagesEl = document.createElement("div");
  messagesEl.className = "messages";
  panel.appendChild(messagesEl);

  // Input row
  const inputRow = document.createElement("div");
  inputRow.className = "input-row";
  const inputField = document.createElement("textarea");
  inputField.className = "input-field";
  inputField.placeholder = "Type a message…";
  inputField.rows = 1;
  const sendBtn = document.createElement("button");
  sendBtn.className = "send-btn";
  sendBtn.innerHTML = \`<svg viewBox="0 0 24 24"><path d="M22 2L11 13M22 2L15 22l-4-9-9-4 20-7z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none"/></svg>\`;
  inputRow.appendChild(inputField);
  inputRow.appendChild(sendBtn);
  panel.appendChild(inputRow);

  // Bubble
  const bubble = document.createElement("button");
  bubble.className = "bubble";
  bubble.setAttribute("aria-label", "Open chat");
  bubble.innerHTML = \`<svg viewBox="0 0 24 24"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none"/></svg>\`;

  shadow.appendChild(panel);
  shadow.appendChild(bubble);

  // State
  let isOpen = false;
  let isWaiting = false;
  const conversation = [];
  let typingEl = null;
  let currentPendingChangeId = null;
  let confirmRowEl = null;

  function togglePanel() {
    isOpen = !isOpen;
    if (isOpen) {
      panel.classList.remove("hidden");
      panel.classList.add("visible");
      inputField.focus();
    } else {
      panel.classList.remove("visible");
      panel.classList.add("hidden");
    }
  }

  bubble.addEventListener("click", togglePanel);
  header.querySelector(".close-btn").addEventListener("click", togglePanel);

  function formatText(text) {
    return text
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      .replace(/\n/g, "<br>");
  }

  function addMessage(role, text) {
    const div = document.createElement("div");
    div.className = "msg " + role;
    div.innerHTML = formatText(text);
    messagesEl.appendChild(div);
    scrollToBottom();
    return div;
  }

  function addErrorMessage(text) {
    const div = document.createElement("div");
    div.className = "msg error";
    div.innerHTML = formatText(text);
    messagesEl.appendChild(div);
    scrollToBottom();
  }

  function showTyping() {
    typingEl = document.createElement("div");
    typingEl.className = "typing";
    typingEl.innerHTML = "<span></span><span></span><span></span>";
    messagesEl.appendChild(typingEl);
    scrollToBottom();
  }

  function hideTyping() {
    if (typingEl) { typingEl.remove(); typingEl = null; }
  }

  function scrollToBottom() {
    messagesEl.scrollTop = messagesEl.scrollHeight;
  }

  function removeConfirmRow() {
    if (confirmRowEl) { confirmRowEl.remove(); confirmRowEl = null; }
    currentPendingChangeId = null;
  }

  function showConfirmRow(pendingChange) {
    removeConfirmRow();
    currentPendingChangeId = pendingChange.id || pendingChange.confirmChangeId || pendingChange;
    confirmRowEl = document.createElement("div");
    confirmRowEl.className = "confirm-row";

    const prBtn = document.createElement("button");
    prBtn.className = "confirm-btn pr";
    prBtn.textContent = "✅ Create PR";

    const undoBtn = document.createElement("button");
    undoBtn.className = "confirm-btn undo";
    undoBtn.textContent = "↩️ Undo";

    confirmRowEl.appendChild(prBtn);
    confirmRowEl.appendChild(undoBtn);
    messagesEl.appendChild(confirmRowEl);
    scrollToBottom();

    prBtn.addEventListener("click", async () => {
      removeConfirmRow();
      await sendConfirm(currentPendingChangeId === null ? pendingChange.id || pendingChange.confirmChangeId || pendingChange : currentPendingChangeId);
    });

    undoBtn.addEventListener("click", () => {
      removeConfirmRow();
      location.reload();
    });
  }

  function applyDomOperations(ops) {
    if (!ops || !Array.isArray(ops)) return;
    ops.forEach(op => {
      try {
        const el = document.querySelector(op.selector);
        if (!el) return;
        if (op.op === "replace_content") { el.innerHTML = op.html; }
        else if (op.op === "replace_attr") { el.setAttribute(op.attr, op.value); }
        else if (op.op === "replace_style") { Object.assign(el.style, op.styles); }
        else if (op.op === "add_class") { el.classList.add(...(Array.isArray(op.classes) ? op.classes : [op.classes])); }
        else if (op.op === "remove_class") { el.classList.remove(...(Array.isArray(op.classes) ? op.classes : [op.classes])); }
        else if (op.op === "insert_after") { el.insertAdjacentHTML("afterend", op.html); }
        else if (op.op === "remove") { el.remove(); }
      } catch (e) { console.warn("DOM op error:", e); }
    });
  }

  async function sendConfirm(confirmChangeId) {
    setWaiting(true);
    showTyping();
    try {
      const res = await fetch(API_ENDPOINT, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ projectId: PROJECT_ID, message: "confirm", confirmChangeId })
      });
      const data = await res.json();
      hideTyping();
      if (data.domOperations) applyDomOperations(data.domOperations);
      if (data.reply) { addMessage("assistant", data.reply); }
      if (data.pendingChange) { showConfirmRow(data.pendingChange); }
    } catch (e) {
      hideTyping();
      addErrorMessage("Sorry, something went wrong. Please try again.");
    } finally {
      setWaiting(false);
    }
  }

  function setWaiting(val) {
    isWaiting = val;
    sendBtn.disabled = val;
    inputField.disabled = val;
  }

  async function sendMessage() {
    const message = inputField.value.trim();
    if (!message || isWaiting) return;
    removeConfirmRow();
    inputField.value = "";
    inputField.style.height = "auto";
    addMessage("user", message);
    conversation.push({ role: "user", content: message });
    setWaiting(true);
    showTyping();

    var pageHtml = document.documentElement.outerHTML.slice(0, 200000);

    try {
      const res = await fetch(API_ENDPOINT, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ projectId: PROJECT_ID, message, pageHtml })
      });
      if (!res.ok) throw new Error("HTTP " + res.status);
      const data = await res.` }} />
      </body>
    </html>
  )
}
